version: '3.3'
services:
  postgresql:
    image: postgres:16.4
    volumes:
      - ~/volumes/jhipster/baribir_db/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=baribir_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5432:5432
